# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# lovelace:
#   mode: yaml

tts:  # Text to speech
  - platform: google_translate
      
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

android_ip_webcam:
  - host: 192.168.31.175
    port: 8080

sensor:
  - platform: mitemp_bt
    rounding: True
    decimals: 1
    period: 60
    log_spikes: False
    use_median: False
    active_scan: False
    hci_interface: 0
    batt_entities: True
    encryptors:
      'A4:C1:38:8B:21:68': !secret bedroom_mitemp_bt_key
    sensor_names:
      'A4:C1:38:8B:21:68': 'bedroom_mitemp_bt'
    report_unknown: False
    whitelist: False

light:
  - platform: xiaomi_miio
    name: desk_bulb
    host: 192.168.31.159
    token: !secret desk_bulb_token

  - platform: xiaomi_miio
    name: closet_bulb
    host: 192.168.31.191
    token: !secret closet_bulb_token

  - platform: xiaomi_miio
    name: bathroom_door_bulb
    host: 192.168.31.186
    token: !secret bathroom_door_bulb_token

  - platform: xiaomi_miio
    name: bedroom_door_bulb
    host: 192.168.31.107
    token: !secret bedroom_door_bulb_token

  - platform: xiaomi_miio
    name:  livingroom_bulb1
    host: 192.168.31.126
    token: !secret livingroom_bulb1_token

  - platform: xiaomi_miio
    name: livingroom_bulb2
    host: 192.168.31.121
    token: !secret livingroom_bulb2_token

yeelight:
  devices:
    192.168.31.144:
      name: light_strip
      transition: 1000
      use_music_mode: true
      save_on_change: true
  custom_effects:
    - name: 'Fire Flicker'
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [1900, 1000, 80]
          - TemperatureTransition: [1900, 2000, 60]
          - SleepTransition:       [1000]
frontend:
  themes:
    gary:
      lovelace-background: center / cover no-repeat url('/local/bg.jpg') fixed
      primary-color: '#D2691E'
      #ha-card-border-radius: '15px'                                                  
      ha-card-background: "rgba(255, 255, 255, 0.5)"       
      ha-card-box-shadow: "0px opx opx rgba(0,0,0,0)"     

google:
  client_id: 931516325886-ucv71si9uvcth9759frjrfl0ef4k046h.apps.googleusercontent.com
  client_secret: !secret google_client_secret

google_assistant:
  project_id: regal-muse-292504
  service_account: !include My Project-1b8d49193d43.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - scene
    - media_player
    - vacuum

spotify:
  client_id: f96d55285aba4eb69161b6a57460dc4d
  client_secret: !secret spotify_client_secret

# spotcast:
#   sp_dc: !secret sp_dc
#   sp_key: !secret sp_key

media_player:
  platform: mpd
  host: 192.168.31.12

